### ISSUE TITLE
Why avoid IO in a Transaction? 

### ISSUE THREAD

**Issue by asheshambasta** [WraithM/opaleye-trans#14]
Hi, my apologies for opening an issue for asking a question but I didn't see an alternative.
I've noticed that the library, an in particular the `Transaction` monad seems to make a conscious effort in avoiding any kind of IO within a `Transaction`. However, I'm not sure I understand the reasoning behind that. The possible reasons I can come up with are: 
- IO can take arbitrarily long, increasing the changes of an open transaction to time out 
- IO can raise exceptions; however, `withTransaction` seems to handle all exceptions raised ensuring that the transaction is closed on the DB (with a rollback) 

--- 

In our experience, this limitation seems overly limiting since it avoids any kind of IO within a transaction. We're using this library in a setting where we need to generate IDs, timestamps etc. on the DB client side. Which means that we need to wire things through and it gets awkward quite fast. 

--- 

So I'd like to understand the reasoning behind this decision. Its quite easy to extend the `Transaction` newtype to also derive a `MonadIO` that does the job. 

Am I missing something?

**Comment by wraithm** [comment]
No, you’re not missing anything. That’s the reasoning, mostly the first one you listed there. You should be able to use the withTransaction and run functions in OpaleyeT if you want to do IO inside of a transaction. I’m hesitant to merge adding MonadIO to Transaction because the point of the Transaction type is to restrict IO, the IO-y alternative is OpaleyeT.

> On Sep 29, 2019, at 11:10 AM, Ashesh Ambasta <notifications@github.com> wrote:
> 
> Hi, my apologies for opening an issue for asking a question but I didn't see an alternative.
> I've noticed that the library, an in particular the Transaction monad seems to make a conscious effort in avoiding any kind of IO within a Transaction. However, I'm not sure I understand the reasoning behind that. The possible reasons I can come up with are:
> 
> 	• IO can take arbitrarily long, increasing the changes of an open transaction to time out
> 	• IO can raise exceptions; however, withTransaction seems to handle all exceptions raised ensuring that the transaction is closed on the DB (with a rollback)
> In our experience, this limitation seems overly limiting since it avoids any kind of IO within a transaction. We're using this library in a setting where we need to generate IDs, timestamps etc. on the DB client side. Which means that we need to wire things through and it gets awkward quite fast.
> 
> So I'd like to understand the reasoning behind this decision. Its quite easy to extend the Transaction newtype to also derive a MonadIO that does the job.
> 
> Am I missing something?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- 


________________________________

Note: This email is for the 
confidential use of the named addressee(s) only and may contain 
proprietary, confidential or privileged information. If you are not the 
intended recipient, you are hereby notified that any review, dissemination 
or copying of this email is strictly prohibited, and to please notify the 
sender immediately and destroy this email and any attachments.

**Comment by asheshambasta** [comment]
@wraithm Thanks for clarifying this. Since this was just a clarification issue, I'm closing this. I understand the reasoning, however.
